// ─── SSE Event Type Constants ────────────────────────────────────────────────

/**
 * All recognised SSE event types emitted by the backend.
 * Components and the SSEManager consume these constants — never raw strings.
 */
export const SSE_EVENTS = {
  // Job lifecycle
  JOB_CREATED: 'JobCreated',
  JOB_SCHEDULED: 'JobScheduled',
  JOB_QUEUED: 'JobQueued',
  JOB_CLAIMED: 'JobClaimed',
  JOB_STARTED: 'JobStarted',
  JOB_COMPLETED: 'JobCompleted',
  JOB_FAILED: 'JobFailed',
  JOB_CANCELLED: 'JobCancelled',

  // Retry lifecycle
  RETRY_PENDING: 'RetryPending',
  RETRY_SCHEDULED: 'RetryScheduled',
  RETRY_EXHAUSTED: 'RetryExhausted',

  // Dead Letter Queue
  DEAD_LETTER_CREATED: 'DeadLetterCreated',
  DEAD_LETTER_REPLAYED: 'DeadLetterReplayed',

  // Worker lifecycle
  WORKER_REGISTERED: 'WorkerRegistered',
  WORKER_HEARTBEAT: 'WorkerHeartbeat',
  WORKER_LOST: 'WorkerLost',
  WORKER_RECOVERED: 'WorkerRecovered',
  WORKER_OFFLINE: 'WorkerOffline',

  // Queue lifecycle
  QUEUE_PAUSED: 'QueuePaused',
  QUEUE_RESUMED: 'QueueResumed',
  QUEUE_DISABLED: 'QueueDisabled',
  QUEUE_ENABLED: 'QueueEnabled',
  QUEUE_DRAINING: 'QueueDraining',

  // Scheduler
  SCHEDULER_PROMOTION_STARTED: 'SchedulerPromotionStarted',
  SCHEDULER_PROMOTION_COMPLETED: 'SchedulerPromotionCompleted',
  SCHEDULER_PROMOTION_FAILED: 'SchedulerPromotionFailed',

  // System
  METRICS_UPDATED: 'MetricsUpdated',
  ACTIVITY_CREATED: 'ActivityCreated',
  NOTIFICATION_CREATED: 'NotificationCreated',
  HEALTH_CHANGED: 'HealthChanged',

  // Internal SSE transport events (not from backend, generated by SSEClient)
  SSE_STATUS: 'sse:status',
  SSE_CONNECTED: 'sse:connected',
  SSE_DISCONNECTED: 'sse:disconnected',
  SSE_RECONNECTING: 'sse:reconnecting',
  SSE_ERROR: 'sse:error',
  SSE_OFFLINE: 'sse:offline',
  SSE_ONLINE: 'sse:online',
} as const;

export type SSEEventType = (typeof SSE_EVENTS)[keyof typeof SSE_EVENTS];

// ─── Live Event Listener ─────────────────────────────────────────────────────

export type LiveEventListener = (data: any) => void;

// ─── EventDispatcher ─────────────────────────────────────────────────────────

export class EventDispatcher {
  private listeners = new Map<string, Set<LiveEventListener>>();

  public subscribe(event: string, callback: LiveEventListener): () => void {
    if (!this.listeners.has(event)) {
      this.listeners.set(event, new Set());
    }
    this.listeners.get(event)!.add(callback);

    return () => {
      const set = this.listeners.get(event);
      if (set) {
        set.delete(callback);
        if (set.size === 0) {
          this.listeners.delete(event);
        }
      }
    };
  }

  public publish(event: string, data: any): void {
    const set = this.listeners.get(event);
    if (set) {
      set.forEach((callback) => {
        try {
          callback(data);
        } catch (err) {
          console.error(`Error in event listener for ${event}:`, err);
        }
      });
    }
  }
}

export const globalEventDispatcher = new EventDispatcher();
