global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'distributed-job-scheduler-api'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['api:3002']
